name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.27'
          cache: true

      - name: Build All Platforms
        run: make build-all

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zeopoxa_exporter-binaries
          path: build/
          if-no-files-found: error